---
title: "correlation"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(psych)
library(rstatix)
```

```{r}
data <- readxl::read_xlsx("Data/params_struc.xlsx") |> 
  mutate(label = factor(label),
         porosity = 1-(BD/2.65),
         Classification = factor(Classification))
```


```{r}
library(ggpubr)
av <- aov(total_c_percent ~ treatment, data = data)
summary(av)
   ggqqplot(data$BD)


TukeyHSD(av)
levene_test(BD ~ treatment, data = data)

dist_undist <- data |> 
  mutate(disturbance = case_when(treatment == "Disturbance" | treatment == "NPK+Disturbance" ~ "disturbed",
                                 .default = "undisturbed"
                                 )) |> 
  mutate(disturbance = factor(disturbance),
         fertilization = case_when(treatment == "NPK" | treatment == "NPK+Disturbance" ~ "fertilized",
                                   .default = "unfertilized"),
         fertilization = factor(fertilization))

av <- aov(total_n_percent ~ fertilization, data = dist_undist)
summary(av)

dist_undist |> 
  ggplot(aes(fertilization,total_c_percent))+
  geom_boxplot()

```
```{r}
av_porosity <- aov(porosity ~ treatment, data = data)
summary(av_porosity)

TukeyHSD(av_porosity)
```


```{r}
corr_data <- bind_cols(data[,2:8],data[,12:16],data[,21],data[,35:44],data[,46])
corr_data2 <- bind_cols(data[,2:8],data[,12:16],data[,21:34])

```

```{r fig.width=8, fig.height=6}
library(rstatix)
m = cor_mat(corr_data, method = "spearman")
x <- m |> 
  gather(-rowname,key = cor_var, value = r)
# corrplot::corrplot(m, method = "number")
x_filtered <- x |> 
  filter(abs(r) > 0.5)
x |> 
  # filter(abs(r) > 0.5) |> 
  #filter(cor_var == "BD" | rowname == "BD") |> 
  ggplot(aes(rowname, cor_var, fill = r)) + 
  geom_tile(size = 3) +
  labs(x = "variables", y = "variables", title = "Correlation plot")+
  geom_text(aes(label = round(r,2)), size = 2)+
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5),
        axis.text = element_text(size = 10))+
   scale_fill_gradient2(low = "red", high = "blue", mid = "white")
#ggsave("Output/corr_overall.jpg", dpi = 300, width = 9,height = 6)
```

```{r fig.width= 9, fig.height= 6}
dist <- data |> 
  filter(treatment == "Disturbance")
dist_corr <- bind_cols(dist[,21],dist[,35:40],dist[,42:44]) |> 
  cor_mat(method = "spearman") |> 
  gather(-rowname,key = cor_var, value = r)

dist_corr |> 
  ggplot(aes(rowname, cor_var, fill = r)) + 
  geom_tile(size = 2.5) +
  theme_minimal()+
  labs(x = "variables", y = "variables", title = "Correlation plot", subtitle = "Treatment - Disturbance")+
  geom_text(aes(label = round(r,2)), size = 2.2)+
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5),
        axis.text = element_text(size = 11))+
   scale_fill_gradient2(low = "red", high = "blue", mid = "white")

#ggsave("Output/corr_dist.jpg", dpi = 300, width = 9,height = 6)
```

```{r}
control <- data |> 
  filter(treatment == "Control")
control_corr <- bind_cols(control[,35:40],control[,21],control[,42:44]) |> 
  cor_mat(method = "spearman") |> 
  gather(-rowname,key = cor_var, value = r)

control_corr |> 
  ggplot(aes(rowname, cor_var, fill = r)) + 
  geom_tile(size = 3) +
  theme_minimal()+
  labs(x = "variables", y = "variables", title = "Correlation plot", subtitle = "Treatment: Control")+
  geom_text(aes(label = round(r,2)), size = 2.5)+
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5),
        axis.text = element_text(size = 12))+
   scale_fill_gradient2(low = "red", high = "blue", mid = "white")

#ggsave("Output/corr_control.jpg", dpi = 300, width = 9,height = 6)
```

```{r}
npk <- data |> 
  filter(treatment == "NPK")
npk_corr <- bind_cols(npk[,35:40],npk[,21],npk[,42:44]) |> 
  cor_mat(method = "spearman") |> 
  gather(-rowname,key = cor_var, value = r)

npk_corr |> 
  ggplot(aes(rowname, cor_var, fill = r)) + 
  geom_tile(size = 3) +
  theme_minimal()+
  labs(x = "variables", y = "variables", title = "Correlation plot", subtitle = "Treatment: NPK")+
  geom_text(aes(label = round(r,2)), size = 2.5)+
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5),
        axis.text = element_text(size = 12))+
   scale_fill_gradient2(low = "red", high = "blue", mid = "white")

#ggsave("Output/corr_npk.jpg", dpi = 300, width = 9,height = 6)
  
```

```{r}
npk_dist <- data |> 
  filter(treatment == "NPK+Disturbance")
npk_dist_corr <- bind_cols(npk_dist[,35:40],npk_dist[,21],npk_dist[,42:44]) |> 
  cor_mat(method = "spearman") |> 
  gather(-rowname,key = cor_var, value = r)

npk_dist_corr |> 
   ggplot(aes(rowname, cor_var, fill = r)) + 
  geom_tile(size = 3) +
  theme_minimal()+
  labs(x = "variables", y = "variables", title = "Correlation plot", subtitle = "Treatment: NPK+Disturbance")+
  geom_text(aes(label = round(r,2)), size = 2.5)+
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5),
        axis.text = element_text(size = 10),
        legend.text = element_text(size = 12))+
   scale_fill_gradient2(low = "red", high = "blue", mid = "white")
#ggsave("Output/corr_npk_dist.jpg", dpi = 300, width = 9,height = 6)
  

```

```{r}
data |> 
   #filter(treatment == "Control") |> 
  ggplot(aes(Sand,transmission_pores))+
  geom_point(aes(color = treatment))+
  geom_smooth(aes(color = treatment),method = "lm", se = F)

data |> 
  ggplot(aes(Sand,storage_pores))+
  geom_point()+
  geom_smooth(method = "lm", se = F)+
  facet_wrap(~treatment)
```

```{r}
data |> 
  ggplot(aes(BD,Field_Capacity))+
  geom_point(aes(color = treatment))+
  geom_smooth(aes(color = treatment),method = "lm", se = F)
```

```{r}
data |> 
  ggplot(aes(BD,air_capacity))+
  geom_point(aes(color = treatment))+
  geom_smooth(method = "lm", se = F)
```

```{r}
numerical_data <- bind_cols(data[,2:8],data[,12:16],data[,21:24],data[,35:44])
```

```{r}
data_normalized <- scale(numerical_data)
colnames(data_normalized) <- c("θr","θs","α1","n1","α2","n2","w","FC", "GCP","PWP","AWC","PWC","BD","RD","TotalC","TotalN","Bonding Space","Residual Pores","Storage Pores","Transmission Pores","Fissures","OM","AC","^%Sand","%Silt","%Clay")

data_pca <- prcomp(data_normalized,scale. = T)
summary(data_pca)

```


```{r}
library(FactoMineR)
library(ggcorrplot)
library(factoextra)
fviz_eig(data_pca,addlabels = T)
```

```{r}
p <- fviz_pca_var(data_pca,
             col.var = "contrib",
             repel = TRUE,
             select.var = list(contrib = 25))
p+
  theme_classic()+
  theme(axis.text = element_text(size = 15))

ggsave("Output/pca.jpg",width = 7,height = 6,dpi = 300)
```

```{r}
fviz_cos2(data_pca, choice = "var", axes = 1:5)
```

```{r}
fviz_pca_ind(data_pca)
```

```{r}
pca_scores <- data_pca$x |> 
  as.data.frame() |> 
  select(PC1:PC4)
```

```{r}
data_postpca <- data |> 
  bind_cols(pca_scores)
```

```{r}
data |> 
  ggplot(aes(thetar,Permanent_Wilting_Point))+
  geom_point()+
  geom_smooth(method = "lm")
```

```{r}
data |> 
  ggplot(aes(porosity,thetas))+
  geom_point()+
  geom_smooth(method = "lm")
```


```{r}
data |> 
  ggplot(aes(treatment,total_c_percent))+
  geom_boxplot()
```

